from django.utils.translation import ugettext_lazy as _

MAX_RECENT = 5
TOP_VIEWS_MAX = 10
PAGINATED_BY = 30
PAGINATION_MAX_SIZE = 50
SHORT_DESCRIPTION_MAX_SIZE = 164
DESCRIPTION_MAX_SIZE = 300

ACCOUNT_PRIVATE = 3
EMAIL_MESSAGE_CONTENT_TYPE = "html"

SETTINGS_BASE_TEMPLATE_INHERIT = "MAILING_BASE_TEMPLATE_INHERIT"
SETTINGS_TEMPLATE_CAMPAIGNS_PAGE = "MAILING_CAMPAIGNS_PAGE"
SETTINGS_TEMPLATE_CAMPAIGN_PAGE  = "MAILING_CAMPAIGN_PAGE"
SETTINGS_TEMPLATE_CAMPAIGN_CREATE_PAGE = "MAILING_CAMPAIGN_CREATE_PAGE"
SETTINGS_TEMPLATE_CAMPAIGN_UPDATE_PAGE = "MAILING_CAMPAIGN_UPDATE_PAGE"
SETTINGS_DEFAULT_MAIL_TEMPLATE = "MAILING_DEFAULT_MAIL_TEMPLATE"
SETTINGS_SEND_ONLY_TO_VERIFIED_USERS = "MAILING_SEND_ONLY_TO_VERIFIED_USERS"
SETTINGS_MAILING_TEMPLATE_CONTEXTS = "MAILING_TEMPLATE_CONTEXTS"
SETTINGS_MAILING_TEMPLATE_CONTEXTS_KEYS = "MAILING_TEMPLATE_CONTEXTS_KEY"
DEFAULT_SEND_ONLY_TO_VERIFIED_USERS = True
DEFAULT_MAILING_CAMPAIGNS_PAGE = "mailing/campaigns.html"
DEFAULT_MAILING_CAMPAIGN_PAGE = "mailing/campaign.html"
DEFAULT_MAILING_CAMPAIGN_CREATE_PAGE ="mailing/campaign_create.html"
DEFAULT_MAILING_CAMPAIGN_UPDATE_PAGE ="mailing/campaign_update.html"

REQUIRED_SETTINGS = [
    SETTINGS_BASE_TEMPLATE_INHERIT, SETTINGS_DEFAULT_MAIL_TEMPLATE, SETTINGS_MAILING_TEMPLATE_CONTEXTS, SETTINGS_MAILING_TEMPLATE_CONTEXTS_KEYS
]


PARAM_CAMPAIGN_MEDIUM_KEY = "email"
PARAM_CAMPAIGN_KEY = "campaign"

PUBLISHED_STATUS_DRAFT = 0
PUBLISHED_STATUS_PUBLISHED = 1
PUBLISHED_STATUS_REVIEW = 2
PUBLISHED_STATUS_REVIEW_FAILED = 3
PUBLISHED_STATUS_DELETED = 4
PUBLISHED_STATUS_SCHEDULED = 5
PUBLISHED_STATUS_SCHEDULED_PRICE = 6

PUBLISHED_STATUS = (
    (PUBLISHED_STATUS_DRAFT, _('draft')),
    (PUBLISHED_STATUS_PUBLISHED, _('published')),
    (PUBLISHED_STATUS_REVIEW, _('review')),
    (PUBLISHED_STATUS_REVIEW_FAILED, _('review failed')),
    (PUBLISHED_STATUS_DELETED, _('deleted')),
    (PUBLISHED_STATUS_SCHEDULED, _('scheduled')),
    (PUBLISHED_STATUS_SCHEDULED_PRICE, _('scheduled price')),
)
